### ISSUE TITLE
Frequency table error

### ISSUE THREAD

**Issue by visze** [exomiser/Exomiser#184] opened 2017-02-07 16:36 UTC
Using the actual 7.3.0-SNAPSHOT version with the exomiser.h2 db from the website (v7.2.1) produces errors reading the frequency tables (exac AFs etc.)

Exomiser was initialized like:

```Java
AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext(ExomiserConfig.class);
ExomiserAnalysis eAnalysis = applicationContext.getBean(ExomiserAnalysis.class);
```

and the ExomiserAnalysis class:

```Java
@Component
public class ExomiserAnalysis {

	@Autowired
	private Exomiser exomiser;

	public AnalysisResults run(Path vcfFile, List<String> hpoIds) {
		AnalysisBuilder analysisBuilder = exomiser.getAnalysisBuilder()
				.pathogenicitySources(EnumSet.of(PathogenicitySource.POLYPHEN, PathogenicitySource.MUTATION_TASTER,
						PathogenicitySource.SIFT))
				.addPathogenicityFilter(true).frequencySources(FrequencySource.ALL_EXTERNAL_FREQ_SOURCES)
				.addFrequencyFilter(1f).analysisMode(AnalysisMode.PASS_ONLY).hpoIds(hpoIds).addPhenixPrioritiser();
		Analysis analysis = analysisBuilder.vcfPath(vcfFile).build();
		return exomiser.run(analysis);
	}

}
```

Maybe I initialize something wrong, or the table is really missing the database...

```
2017-02-07 17:28:34.944 [main] ERROR org.monarchinitiative.exomiser.core.dao.DefaultFrequencyDao - Error executing frequency query: 
org.h2.jdbc.JdbcSQLException: Table "frequency" not found; SQL statement:
SELECT rsid, dbSNPmaf, espEAmaf, espAAmaf, espAllmaf, exacAFRmaf,  exacAMRmaf, exacEASmaf, exacFINmaf, exacNFEmaf, exacOTHmaf, exacSASmaf FROM frequency WHERE chromosome = ? AND position = ? AND ref = ? AND alt = ? ORDER BY dbsnpmaf desc, espeamaf desc, espaamaf desc, espallmaf desc  [42102-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5388)
	at org.h2.command.Parser.readTableFilter(Parser.java:1257)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1896)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2044)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1890)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1711)
	at org.h2.command.Parser.parseSelect(Parser.java:1699)
	at org.h2.command.Parser.parsePrepared(Parser.java:445)
	at org.h2.command.Parser.parse(Parser.java:317)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.prepareCommand(Parser.java:254)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1202)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:290)
	at org.monarchinitiative.exomiser.core.dao.DefaultFrequencyDao.createPreparedStatement(DefaultFrequencyDao.java:113)
	at org.monarchinitiative.exomiser.core.dao.DefaultFrequencyDao.getFrequencyData(DefaultFrequencyDao.java:90)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:414)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy43.getFrequencyData(Unknown Source)
	at org.monarchinitiative.exomiser.core.factories.VariantDataServiceImpl.getVariantFrequencyData(VariantDataServiceImpl.java:70)
	at org.monarchinitiative.exomiser.core.filters.FrequencyDataProvider.provideVariantData(FrequencyDataProvider.java:36)
	at org.monarchinitiative.exomiser.core.filters.AbstractFilterDataProvider.runFilter(AbstractFilterDataProvider.java:48)
	at org.monarchinitiative.exomiser.core.filters.AbstractFilterDataProvider.runFilter(AbstractFilterDataProvider.java:1)
	at org.monarchinitiative.exomiser.core.filters.SimpleVariantFilterRunner.runFilterAndAddResult(SimpleVariantFilterRunner.java:83)
	at org.monarchinitiative.exomiser.core.filters.SimpleVariantFilterRunner.run(SimpleVariantFilterRunner.java:79)
	at org.monarchinitiative.exomiser.core.analysis.PassOnlyAnalysisRunner.lambda$5(PassOnlyAnalysisRunner.java:71)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.monarchinitiative.exomiser.core.analysis.PassOnlyAnalysisRunner.lambda$1(PassOnlyAnalysisRunner.java:71)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner.loadAndFilterVariants(AbstractAnalysisRunner.java:170)
	at org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner.run(AbstractAnalysisRunner.java:111)
	at org.monarchinitiative.exomiser.core.Exomiser.run(Exomiser.java:60)
	at de.charite.compbio.exomiserbenchmark.exomiser.ExomiserAnalysis.run(ExomiserAnalysis.java:35)
	at de.charite.compbio.exomiserbenchmark.Main.runBenchmark(Main.java:226)
	at de.charite.compbio.exomiserbenchmark.Main.run(Main.java:108)
	at de.charite.compbio.exomiserbenchmark.Main.main(Main.java:92)
```

**Comment by julesjacobsen** [comment] 2017-02-07 16:38
Hmm, where did you get the database from exactly? Did you check it's not corrupted? I'm using exactly this combination without any problem.

**Comment by visze** [comment] 2017-02-07 17:09
Well when I use the cli it works fine with the db... so I guess inlcuded exomiser wrongly as a library.

I followed your rules in: `https://github.com/exomiser/Exomiser/tree/development` But couldn't get it running. Using a config like:

```Java
@EnableExomiser
public class MainConfig {

}
```
returns lots of errors! The private `ExomiserProperties properties` in `ExomiserAutoConfiguration` is always emtpy. 

So I try to adapt the `MainConfig` of the cli. Then it worked fine using the jannovar transcript db etc... but it seems to have problems with the database...

**Comment by julesjacobsen** [comment] 2017-02-07 17:15
Are you using Spring correctly? Without seeing your whole project, I can't say for sure what the problem is.

Check out the [demo project](https://github.com/exomiser/exomiser-demo) for how to set-up a fully working application.

**Comment by visze** [comment] 2017-02-07 17:19
As you know: I have no idea about spring :-)

I will try to follow the files in the demo project and I will come to you If I can work it out (or not)

**Comment by visze** [comment] 2017-02-07 17:26
```
 Could not resolve placeholder 'jarFilePath' in string value "file:${jarFilePath}/application.properties"
```

**Comment by visze** [comment] 2017-02-07 17:43
Sorry same error! These are my only two classes:

```Java
@EnableExomiser
@SpringBootApplication
public class Main {

	private static ConfigurableApplicationContext applicationContext;

	
	public static void main(String[] args) throws IOException {
		System.setProperty("jarFilePath", jarFilePath().toString());
		applicationContext = SpringApplication.run(Main.class, args);
		 Main main = new Main();
		 main.run(args);
	}

	private void run(String[] args) throws IOException {

		runBenchmark(args);
	}

	private static Path jarFilePath() {
		CodeSource codeSource = Main.class.getProtectionDomain().getCodeSource();
		try {
			return Paths.get(codeSource.getLocation().toURI()).getParent();
		} catch (URISyntaxException ex) {
			logger.error("Unable to find jar file", ex);
			throw new RuntimeException("Unable to find jar file", ex);
		}
	}

	public void runBenchmark(String[] args) throws IOException {
		ExomiserAnalysis eAnalysis = applicationContext.getBean(ExomiserAnalysis.class);
	
		File tmp = new File("/tmp/test7406358637927487227.vcf.gz");
		AnalysisResults analysisResults = eAnalysis.run(tmp.toPath(), Arrays.asList("HP:0012736", "HP:0005590","HP:0005280", "HP:0000938", "HP:0002719", "HP:0000506"));
	}

}
```

and

```Java
@Controller
public class ExomiserAnalysis {

	private final Exomiser exomiser;

	@Autowired
	public ExomiserAnalysis(Exomiser exomiser) {
	        this.exomiser = exomiser;
	}

	public AnalysisResults run(Path vcfFile, List<String> hpoIds) {
		AnalysisBuilder analysisBuilder = exomiser.getAnalysisBuilder()
				.pathogenicitySources(EnumSet.of(PathogenicitySource.POLYPHEN, PathogenicitySource.MUTATION_TASTER,
						PathogenicitySource.SIFT))
				.addPathogenicityFilter(true).frequencySources(FrequencySource.ALL_EXTERNAL_FREQ_SOURCES)
				.addFrequencyFilter(1f).analysisMode(AnalysisMode.PASS_ONLY).hpoIds(hpoIds).addPhenixPrioritiser();
		Analysis analysis = analysisBuilder.vcfPath(vcfFile).build();
		return exomiser.run(analysis);
	}

```

**Comment by julesjacobsen** [comment] 2017-02-08 09:57
Yep, you're doing it wrong. Too much code. What are you trying to build? A command-line or a web application?

**Comment by visze** [comment] 2017-02-08 10:03
none of both. Using it as a library (so it has a cli, but this totally different). It is basically a benchmark framework for BOQA playing around with settings, hpo-terms, inputs etc. and then using the final ranking fore some statistics

**Comment by julesjacobsen** [comment] 2017-02-08 10:13
Then why not just clone the demo project and tweak that to run the new phenix? It will do exactly what you want:

```
java -jar exomiser-demo-0.0.1-SNAPSHOT.jar --exomiser.data-directory=/home/user/exomiser-dir/data
```
Run your sample:
```
http://localhost:8080/analyse/?vcf=/tmp/test7406358637927487227.vcf.gz&phenotypes=HP:0012736,HP:0005590,HP:0005280,HP:0000938,HP:0002719,HP:0000506&format=HTML
```

**Comment by visze** [comment] 2017-02-08 10:22
thx for the help. But I do not want to use the rest stuff. i want to use it in my javacode, because I am doing iterative things and I want to get an AnalysisResults as result (no html output etc.) 
The second thing is, that the tmp file right now is just a workaround. I build the test cases in memory and I want to use my Stream of VariantContext directly (see #183). Right now I just generate a tmp file an pars it again 8and this several thousand times). It will speed up everything if I can avoid that. 

But first I just want to get exomiser run as a library in another javaproject. That should not be that complicated. Spending now about one week on it an didn't get it to run. So I will be grateful for any help.

**Comment by julesjacobsen** [comment] 2017-02-08 10:36
```
@EnableExomiser
@SpringBootApplication
public class Main {

	public static void main(String[] args) throws IOException {
		SpringApplication.run(Main.class, args);
	}
}
```

To run in from the command line using ```java -jar exomiser-demo-0.0.1-SNAPSHOT.jar --exomiser.data-directory=/home/user/exomiser-dir/data --vcf=/tmp/test7406358637927487227.vcf.gz --hpo=HP:0012736,HP:0005590,HP:0005280,HP:0000938,HP:0002719,HP:0000506```

```
@Component
public class PhenixBenchmarker implements ApplicationRunner {

    private final Exomiser exomiser;
    
    public PhenixBenchmarker(Exomiser exomiser) {
	this.exomiser = exomiser;
    }


    @Override
    public void run(ApplicationArguments applicationArguments) throws Exception {
        List<String> fileName = applicationArguments.getOptionValues("vcf");
        Path vcfPath = Paths.get(filename.get(0));

        List<String> hpoIds= applicationArguments.getOptionValues("hpo");
        
        //do something with this:
        run(vcfPath, hpoIds)
    
    }

    private AnalysisResults run(Path vcfFile, List<String> hpoIds) {
        AnalysisBuilder analysisBuilder = exomiser.getAnalysisBuilder()
                .pathogenicitySources(EnumSet.of(PathogenicitySource.POLYPHEN, PathogenicitySource.MUTATION_TASTER,
                        PathogenicitySource.SIFT))
                .addPathogenicityFilter(true).frequencySources(FrequencySource.ALL_EXTERNAL_FREQ_SOURCES)
                .addFrequencyFilter(1f).analysisMode(AnalysisMode.PASS_ONLY).hpoIds(hpoIds).addPhenixPrioritiser();
        Analysis analysis = analysisBuilder.vcfPath(vcfFile).build();
        return exomiser.run(analysis);
    }
}
```

I haven't checked this actually works, mind you...

**Comment by visze** [comment] 2017-02-08 10:39
thx I will try it

**Comment by julesjacobsen** [comment] 2017-02-08 10:51
I agree about the ```Stream<VariantContext>``` issue, but this isn't going to happen for a bit. You absolutely want to iterate over a list of files keeping the exomiser open in memory as this will save you the jannovar start-up time - i.e. call ```run(vcfPath, hpoIds)``` over every file you have. Also if you're using the same variants enable caching in your application.properties.

If you're just running a phenix benchmark, do you need the variants at all? You could use the prioritiser directly perhaps.

**Comment by visze** [comment] 2017-02-08 12:21
Hi, year sometimes it will be easier to run the prioritiser right away.  But now it is time to run it together with the variants to see if the disease-causing mutation (gene) is ranked on top 1 of an exome. At this point we cannot neglect the variants. (and the "exome" used is really dynamic and it changes from test to test.... )

I tried it with your approach. Does not work! :-) Same problem with the frequencies! Then I tried using a new exomiser.h2.db. Maybe the file is corrupted. But I get the same (frequency) error... :-(

Then I used (to rule out everything) the exomiser-demo with the same data directory. It works...

**Comment by visze** [comment] 2017-02-08 12:24
short update info: I have to set the jarFileFath property in your example. Otherwise it will give me an error right away!
```Java
System.setProperty("jarFilePath", jarFilePath().toString());
```

**Comment by visze** [comment] 2017-02-08 12:37
has it something to do that I have to use a source path like `org.monarch...`

**Comment by visze** [comment] 2017-02-08 12:55
maybe let's try to get the exomiser demo to run using the CLI: Here I have integrated your code. But it fails:

`https://github.com/visze/exomiser-demo/tree/exomiser-cli-demo`

**Comment by julesjacobsen** [comment] 2017-02-08 13:29
Are you running it from the directory where the jar file is? You might need to use the full system path instead of the relative path. I think we should try talking about this closer to real-time.

**Comment by julesjacobsen** [comment] 2017-02-08 13:31
e.g. Skype.

**Comment by julesjacobsen** [comment] 2017-02-08 15:35
I'm going to close this - I think there is an issue at your end seeing as you could run the code I built OK, so it's not a database issue per-se. I'll make another cli demo application which you can fork and extend, from source code of the working jar I sent you.

**Closed by julesjacobsen** 2017-02-08 15:35 UTC
