### ISSUE TITLE
exomiser_variant_tsv_output_CLINVAR_PRIMARY_INTERPRETATION_column, frequency scores and disease associations

### ISSUE THREAD

**Issue by reversetosanam** [exomiser/Exomiser#560] opened 2024-05-11 11:46 UTC
CLINVAR_PRIMARY_INTERPRETATION_column in .tsv output file shows 'not provided' instead of 'criteria provided, conflicting classifications', even in .html file there is showing 'no assertion criteria provided', please help with that

**Comment by reversetosanam** [comment] 2024-05-11 11:51
even in CLINVAR_STAR_RATING column, 0 star is given by exomiser to the variants that are having conflicting classifications but it is usually 1 on clinvar database.

**Comment by julesjacobsen** [comment] 2024-05-13 12:50
Can you provide the actual cases, please? Also, what is the version of the Exomiser data you're viewing? ClinVar is updated weekly whereas Exomiser is updated twice a year, so there will inevitably be some differences.

**Comment by reversetosanam** [comment] 2024-05-14 04:18
Kindly check these columns in attached excel sheet.
![Screenshot from 2024-05-14 09-44-42](https://github.com/exomiser/Exomiser/assets/169533077/e1c69ad6-c24a-4494-a22d-5907d0c30750)

I am using Exomiser 14.0.0, the latest one.

**Comment by julesjacobsen** [comment] 2024-05-16 15:25
Ah! Thank you. Yes I see now.

These rows:
CLINVAR_VARIATION_ID | CLINVAR_PRIMARY_INTERPRETATION | CLINVAR_STAR_RATING
--------|-------------|-----------|
361482 | NOT_PROVIDED | 0
179002 | NOT_PROVIDED | 0
795060 | NOT_PROVIDED | 0
372319 | NOT_PROVIDED | 0

Should be:
CLINVAR_VARIATION_ID | CLINVAR_PRIMARY_INTERPRETATION | CLINVAR_STAR_RATING
--------|-------------|-----------|
361482 | CONFLICTING_PATHOGENICITY_INTERPRETATIONS | 1
179002 | CONFLICTING_PATHOGENICITY_INTERPRETATIONS | 1
795060 | CONFLICTING_PATHOGENICITY_INTERPRETATIONS | 1
372319 | CONFLICTING_PATHOGENICITY_INTERPRETATIONS | 1

I've found the cause - for some reason ClinVar changed the `CLNSIG` value for these from `CLNSIG=Conflicting_interpretations_of_pathogenicity` to `CLNSIG=Conflicting_classifications_of_pathogenicity` in the VCF files used to produce the Exomiser ClinVar data. Instead of failing, this fell back to the default value of `NOT_PROVIDED`.

**Comment by reversetosanam** [comment] 2024-05-17 04:35
So, is it now resolved ?

One more thing that i noticed in exomiser 14.0.0 annotations is the frequency data, it is not giving frequency data for some variants but i get it using other annotation tools like annovar and on the official databases as well like gnomad.

**Comment by reversetosanam** [comment] 2024-05-17 04:42
and is it possible to get all phenotype associated diseases as per the phenoscore, the information is available in .html file but in variants.tsv file, disease with highest phenoscore is mentioned. Is it possible to add a column that mentions all associated diseases.

**Comment by julesjacobsen** [comment] 2024-05-19 14:23
> Thank you for looking into it, i hope it'll get resolved soon?
> 
> One more thing that i noticed in exomiser 14.0.0 annotations is the frequency data, it is not giving frequency data for some variants but i get it using other annotation tools like annovar and on the official databases as well like gnomad.

Examples please...

**Comment by julesjacobsen** [comment] 2024-05-19 14:24
> and is it possible to get all phenotype associated diseases as per the phenoscore, the information is available in .html file but in variants.tsv file, disease with highest phenoscore is mentioned. Is it possible to add a column that mentions all associated diseases.

Have you checked in the `genes.tsv` output?

**Comment by julesjacobsen** [comment] 2024-07-01 16:51
ClinVar issues are fixed in #562 data. If you still have other issues, please open a separate ticket.

**Closed by julesjacobsen** 2024-07-01 16:51 UTC
