### ISSUE TITLE
Finished Analysis .. but failing.

### ISSUE THREAD

**Issue by rfarhad** [exomiser/Exomiser#570] opened 2024-09-11 08:55 UTC
2024-09-10T12:11:13.815+03:00  INFO 827103 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Finished analysis in 30m 40s 928ms (1840928 ms)
2024-09-10T12:11:13.816+03:00  INFO 827103 --- [           main] o.m.e.cli.ExomiserCommandLineRunner      : Writing results...
2024-09-10T12:11:35.182+03:00  INFO 827103 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-09-10T12:11:35.197+03:00 ERROR 827103 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
	at org.monarchinitiative.exomiser.core.model.frequency.FrequencyData.frequency(FrequencyData.java:169) ~[exomiser-core-14.0.0.jar:na]
	at org.monarchinitiative.exomiser.core.model.frequency.FrequencyData.maxFrequency(FrequencyData.java:327) ~[exomiser-core-14.0.0.jar:na]
	at org.monarchinitiative.exomiser.core.writers.TsvVariantResultsWriter.buildVariantRecord(TsvVariantResultsWriter.java:174) ~[exomiser-core-14.0.0.jar:na]
	at org.monarchinitiative.exomiser.core.writers.TsvVariantResultsWriter.lambda$writeData$0(TsvVariantResultsWriter.java:112) ~[exomiser-core-14.0.0.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[na:na]
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[na:na]
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[na:na]
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at org.monarchinitiative.exomiser.core.writers.TsvVariantResultsWriter.writeData(TsvVariantResultsWriter.java:113) ~[exomiser-core-14.0.0.jar:na]
	at org.monarchinitiative.exomiser.core.writers.TsvVariantResultsWriter.writeFile(TsvVariantResultsWriter.java:88) ~[exomiser-core-14.0.0.jar:na]
	at org.monarchinitiative.exomiser.core.writers.AnalysisResultsWriter.writeToFile(AnalysisResultsWriter.java:69) ~[exomiser-core-14.0.0.jar:na]
	at org.monarchinitiative.exomiser.core.writers.AnalysisResultsWriter.writeToFile(AnalysisResultsWriter.java:55) ~[exomiser-core-14.0.0.jar:na]
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runJob(ExomiserCommandLineRunner.java:92) ~[exomiser-cli-14.0.0.jar:na]
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runJobs(ExomiserCommandLineRunner.java:65) ~[exomiser-cli-14.0.0.jar:na]
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(ExomiserCommandLineRunner.java:60) ~[exomiser-cli-14.0.0.jar:na]
	at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.4.jar:6.1.4]
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.4.jar:6.1.4]
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.4.jar:6.1.4]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774) ~[spring-boot-3.2.3.jar:3.2.3]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.monarchinitiative.exomiser.cli.Main.main(Main.java:53) ~[exomiser-cli-14.0.0.jar:na]

**Comment by rfarhad** [comment] 2024-09-11 08:56
The output files are generated, however the log files indicate failure.

**Comment by julesjacobsen** [comment] 2024-09-12 16:48
This is a duplicate of https://github.com/exomiser/Exomiser/issues/565 - please update your version of Exomiser to [14.0.1](https://github.com/exomiser/Exomiser/releases/tag/14.0.1)

**Closed by julesjacobsen** 2024-09-12 16:48 UTC
